Repository EphemeralSpace/ephemeral-space, pull requests merged in 2025-06, with the labels that each got.

#16 Shuttle tube walls
  Resources/Locale/en-US/_ES/construction/recipes.ftl
  Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
  Resources/Prototypes/_ES/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/_ES/Recipes/structures.yml
  Resources/Textures/_ES/Structures/Walls/tube.rsi/full.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/meta.json
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state0.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state1.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state2.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state3.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state4.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state5.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state6.png
  Resources/Textures/_ES/Structures/Walls/tube.rsi/state7.png
  Resources/Textures/_ES/Structures/Walls/tube_diagonal.rsi/meta.json
  Resources/Textures/_ES/Structures/Walls/tube_diagonal.rsi/state0.png
  Resources/Textures/_ES/Structures/Walls/tube_diagonal.rsi/state1.png
Labels: S: Untriaged, size/M

#18 Duct tape
  Resources/Locale/en-US/_ES/stack/stacks.ftl
  Resources/Prototypes/_ES/Entities/Objects/Materials/tape.yml
  Resources/Prototypes/_ES/Stacks/Materials/parts.yml
  Resources/Textures/_ES/Objects/Materials/tape.rsi/icon.png
  Resources/Textures/_ES/Objects/Materials/tape.rsi/icon2.png
  Resources/Textures/_ES/Objects/Materials/tape.rsi/icon3.png
  Resources/Textures/_ES/Objects/Materials/tape.rsi/inhand-left.png
  Resources/Textures/_ES/Objects/Materials/tape.rsi/inhand-right.png
  Resources/Textures/_ES/Objects/Materials/tape.rsi/meta.json
Labels: S: Untriaged, size/S

#20 give spawn menu a facelift
  Content.Client/Lobby/LobbyState.cs
  Content.Client/_ES/Spawning/SpawningWindow.cs
  Content.Client/_ES/Spawning/SpawningWindow.xaml
  Resources/Locale/en-US/_ES/spawning/spawn-menu.ftl
Labels: S: Untriaged, size/M

#21 Engineering Overalls
  Resources/Prototypes/_ES/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/equipped-INNERCLOTHING-jumpsuit.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/equipped-INNERCLOTHING-shirt.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/icon-jumpsuit.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/icon-shirt.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/inhand-left-jumpsuit.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/inhand-left-shirt.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/inhand-right-jumpsuit.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/inhand-right-shirt.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/engineering.rsi/meta.json
Labels: S: Untriaged, size/S

#15 Auditions: random cast generation
  Content.Server/_ES/Auditions/AuditionsSystem.cs
  Content.Shared/_ES/Auditions/BackgroundPrototype.cs
  Content.Shared/_ES/Auditions/CharacterComponent.cs
  Content.Shared/_ES/Auditions/ProducerComponent.cs
  Content.Shared/_ES/Auditions/RelationshipPrototype.cs
  Content.Shared/_ES/Auditions/SharedAuditionsSystem.cs
  Content.Shared/_ES/Auditions/SocialGroupComponent.cs
  Content.Shared/_ES/CCVar/ECCVars.cs
  Resources/Locale/en-US/_ES/backgrounds/backgrounds.ftl
  Resources/Locale/en-US/_ES/commands/toolshed-descriptions.ftl
  Resources/Locale/en-US/_ES/relationships/basic.ftl
  Resources/Prototypes/_ES/Backgrounds/backgrounds.yml
  Resources/Prototypes/_ES/Backgrounds/pools.yml
  Resources/Prototypes/_ES/Relationships/pools.yml
  Resources/Prototypes/_ES/Relationships/relationships.yml
Labels: size/M

#25 Wallets
  Resources/Prototypes/_ES/Entities/Objects/Misc/wallets.yml
  Resources/Textures/_ES/Objects/Misc/wallet.rsi/icon-logo-PIT.png
  Resources/Textures/_ES/Objects/Misc/wallet.rsi/icon.png
  Resources/Textures/_ES/Objects/Misc/wallet.rsi/inhand-left.png
  Resources/Textures/_ES/Objects/Misc/wallet.rsi/inhand-right.png
  Resources/Textures/_ES/Objects/Misc/wallet.rsi/meta.json
Labels: S: Untriaged, size/S

#31 Add wall keypads
  Content.Client/_ES/Keypad/ESKeypadSystem.cs
  Content.Client/_ES/Keypad/Ui/ESKeypadBui.cs
  Content.Client/_ES/Keypad/Ui/ESKeypadControl.cs
  Content.Client/_ES/Keypad/Ui/ESKeypadControl.xaml
  Content.Client/_ES/Keypad/Ui/ESKeypadWindow.cs
  Content.Client/_ES/Keypad/Ui/ESKeypadWindow.xaml
  Content.Server/_ES/Keypad/ESKeypadSystem.cs
  Content.Shared/_ES/Construction/Conditions/ESKeypadUnlockedCondition.cs
  Content.Shared/_ES/Keypad/Components/ESKeypadComponent.cs
  Content.Shared/_ES/Keypad/ESSharedKeypadSystem.cs
  Resources/Locale/en-US/_ES/construction/graphs.ftl
  Resources/Locale/en-US/_ES/device-linking/source-ports.ftl
  Resources/Locale/en-US/_ES/keypad/keypad.ftl
  Resources/Prototypes/_ES/DeviceLinking/source_ports.yml
  Resources/Prototypes/_ES/Entities/Objects/Devices/circuits.yml
  Resources/Prototypes/_ES/Entities/Structures/Wallmounts/keypad.yml
  Resources/Prototypes/_ES/Recipes/Graphs/wallmounts.yml
  Resources/Prototypes/_ES/Recipes/wallmounts.yml
  Resources/Prototypes/_ES/tags.yml
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/blank_mod.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/card_mod.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/cyborg_upgrade.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/cyborg_upgrade1.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/cyborg_upgrade2.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/cyborg_upgrade3.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/cyborg_upgrade4.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/gooncode.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/id_mod.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/inhand-left.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/inhand-right.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/mainboard.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/mcontroller.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/meta.json
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/planning_frame.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/power_mod.png
  Resources/Textures/_ES/Objects/Devices/circuits.rsi/std_mod.png
  Resources/Textures/_ES/Structures/Wallmounts/keypad.rsi/base.png
  Resources/Textures/_ES/Structures/Wallmounts/keypad.rsi/frame-0.png
  Resources/Textures/_ES/Structures/Wallmounts/keypad.rsi/frame-1.png
  Resources/Textures/_ES/Structures/Wallmounts/keypad.rsi/frame-2.png
  Resources/Textures/_ES/Structures/Wallmounts/keypad.rsi/locked.png
  Resources/Textures/_ES/Structures/Wallmounts/keypad.rsi/meta.json
  Resources/Textures/_ES/Structures/Wallmounts/keypad.rsi/unlocked.png
Labels: S: Untriaged, size/M

#32 update code to have prefixes
  Content.Client/Lobby/LobbyState.cs
  Content.Client/_ES/Spawning/ESSpawningWindow.cs
  Content.Client/_ES/Spawning/ESSpawningWindow.xaml
  Content.Server/GameTicking/GameTicker.Spawning.cs
  Content.Server/_ES/Auditions/Components/ESStationCastComponent.cs
  Content.Server/_ES/Auditions/ESAuditionsSystem.cs
  Content.Shared/_ES/Auditions/ESBackgroundPrototype.cs
  Content.Shared/_ES/Auditions/ESCharacterComponent.cs
  Content.Shared/_ES/Auditions/ESProducerComponent.cs
  Content.Shared/_ES/Auditions/ESRelationshipPrototype.cs
  Content.Shared/_ES/Auditions/ESSharedAuditionsSystem.cs
  Content.Shared/_ES/Auditions/ESSocialGroupComponent.cs
  Content.Shared/_ES/CCVar/ESCVars.cs
  Resources/Prototypes/_ES/Backgrounds/backgrounds.yml
  Resources/Prototypes/_ES/Relationships/relationships.yml
Labels: S: Untriaged, size/M

#33 radio falloff
  Content.Server/Radio/EntitySystems/RadioSystem.cs
  Content.Server/_ES/Radio/Components/ESRadioFalloffComponent.cs
  Content.Server/_ES/Radio/ESRadioSystem.cs
  Resources/Locale/en-US/_ES/radio/falloff.ftl
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/_ES/Datasets/radio.yml
Labels: S: Untriaged, size/M

#35 Psycho Body Prototypes
  Content.Server/Cargo/Systems/PricingSystem.cs
  Resources/Prototypes/_ESP/Entities/Mobs/NPCs/carp.yml
  Resources/Prototypes/_ESP/Entities/Mobs/NPCs/simplemob.yml
  Resources/Prototypes/_ESP/Entities/Mobs/Player/dragon.yml
  Resources/Prototypes/_ESP/Entities/Mobs/Player/human.yml
  Resources/Prototypes/_ESP/Entities/Mobs/Species/base.yml
  Resources/Prototypes/_ESP/Entities/Mobs/Species/human.yml
  Resources/Prototypes/_ESP/Entities/Mobs/base.yml
Labels: S: Untriaged, size/M
