Repository EphemeralSpace/ephemeral-space, pull requests merged in 2025-07, with the labels that each got.

#36 Captain Clothing
  Resources/Prototypes/_ES/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/_ES/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/_ES/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/equipped-HELMET-color.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/equipped-HELMET.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/icon-color.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/icon.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/inhand-left-color.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/inhand-left.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/inhand-right-color.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/inhand-right.png
  Resources/Textures/_ES/Clothing/Head/Hats/captain.rsi/meta.json
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/equipped-OUTERCLOTHING-color.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/icon-color.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/icon.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/inhand-left-color.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/inhand-left.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/inhand-right-color.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/inhand-right.png
  Resources/Textures/_ES/Clothing/OuterClothing/Coats/captain.rsi/meta.json
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/captain.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/captain.rsi/icon.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/captain.rsi/inhand-left.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/captain.rsi/inhand-right.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/captain.rsi/meta.json
Labels: S: Untriaged, size/M

#29 Adds a test/debug ship
  Resources/Maps/_ES/testship.yml
Labels: S: Untriaged, size/L

#38 Respawning
  Content.Client/Lobby/LobbyState.cs
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
  Content.Client/_ES/Spawning/ESSpawningSystem.cs
  Content.Client/_ES/Spawning/Ui/ESSpawningWindow.cs
  Content.Client/_ES/Spawning/Ui/ESSpawningWindow.xaml
  Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs
  Content.Server/Mind/MindSystem.cs
  Content.Server/_ES/Auditions/ESAuditionsSystem.cs
  Content.Server/_ES/Spawning/ESSpawningSystem.cs
  Content.Shared/_ES/CCVar/ESCVars.cs
  Content.Shared/_ES/Spawning/Components/ESRespawnTrackerComponent.cs
  Content.Shared/_ES/Spawning/ESSharedSpawningSystem.cs
  Resources/Locale/en-US/_ES/spawning/spawn-menu.ftl
Labels: S: Untriaged, size/M

#39 Better appearances + personality
  Content.Server/_ES/Auditions/ESAuditionsSystem.cs
  Content.Shared/Humanoid/Prototypes/ESSpeciesPrototype.cs
  Content.Shared/_ES/Auditions/Components/ESCharacterComponent.cs
  Content.Shared/_ES/Auditions/Components/ESProducerComponent.cs
  Content.Shared/_ES/Auditions/Components/ESSocialGroupComponent.cs
  Content.Shared/_ES/Auditions/ESSharedAuditionsSystem.Appearance.cs
  Content.Shared/_ES/Auditions/ESSharedAuditionsSystem.cs
  Content.Shared/_ES/Random/ESRandomHelpers.cs
  Resources/Locale/en-US/_ES/character/personality.ftl
  Resources/Prototypes/Species/human.yml
  Resources/Prototypes/_ES/Datasets/personality.yml
Labels: S: Untriaged, size/M

#43 Fueled Thrusters (by roomba)
  Content.Server/Atmos/EntitySystems/AtmoshpereSystem.EsHelpers.cs
  Content.Server/Shuttles/Components/ThrusterComponent.cs
  Content.Server/Shuttles/Systems/ThrusterSystem.cs
  Resources/Prototypes/_ES/Entities/Structures/Shuttles/thrusters.yml
Labels: S: Untriaged, size/L

#46 Add procgen grids to multistation config
  Content.Server/_ES/Multistation/Components/ESMultistationMapComponent.cs
  Content.Server/_ES/Multistation/ESMultistationConfigPrototype.cs
  Content.Server/_ES/Multistation/ESMultistationSystem.cs
  Resources/Prototypes/_ES/Maps/multistation.yml
Labels: S: Untriaged, size/M

#47 brush up test map
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_ES/estestship_grid.yml
Labels: S: Untriaged, size/L

#53 Add equipment override for stations
  Content.Server/Station/Systems/StationSpawningSystem.cs
  Content.Shared/_ES/Spawning/Components/ESStationGearOverrideComponent.cs
  Resources/Prototypes/_ES/Roles/Jobs/gear_russian.yml
Labels: S: Untriaged, size/S

#59 Rules + Space Law Rewrite
  Resources/Prototypes/Guidebook/security.yml
  Resources/Prototypes/_ES/Guidebook/rules.yml
  Resources/Prototypes/_ES/Guidebook/space_law.yml
  Resources/ServerInfo/_ES/Guidebook/Rules.xml
  Resources/ServerInfo/_ES/Guidebook/SpaceLaw.xml
Labels: S: Untriaged, size/M, S: Needs Review
