Repository EphemeralSpace/ephemeral-space, pull requests merged in 2025-10, with the labels that each got.

#183 add vending machine spawners + global restock box
  Content.IntegrationTests/Tests/VendingMachineRestockTest.cs
  Content.Server/Destructible/Thresholds/Behaviors/DumpRestockInventory.cs
  Content.Shared/VendingMachines/SharedVendingMachineSystem.Restock.cs
  Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml
  Resources/Prototypes/_ES/Entities/Markers/Spawners/Random/vendors.yml
  Resources/Prototypes/_ES/Entities/Objects/Devices/restock.yml
  Resources/Textures/_ES/Markers/spawners.rsi/meta.json
  Resources/Textures/_ES/Markers/spawners.rsi/vendor-drink.png
  Resources/Textures/_ES/Markers/spawners.rsi/vendor-snack.png
Labels: S: Untriaged, size/S, S: Needs Review

#184 NT Toast
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Server/_ES/Maps/NameGenerators/ESSimpleNameGenerator.cs
  Resources/Maps/_ES/toast.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_ES/Maps/toast.yml
Labels: S: Untriaged, S: Needs Review, size/XL

#182 Traitor caches and Marauder Mask
  Content.Client/UserInterface/Systems/Character/CharacterUIController.cs
  Content.Client/_ES/Masks/Traitor/ESMaskCacheSystem.cs
  Content.Server/Roles/RoleSystem.cs
  Content.Server/_ES/Masks/ESMaskSystem.cs
  Content.Server/_ES/Masks/Traitor/ESMaskCacheSystem.cs
  Content.Shared/_ES/Masks/ESMaskPrototype.cs
  Content.Shared/_ES/Masks/Traitor/Components/ESCeilingCacheComponent.cs
  Content.Shared/_ES/Masks/Traitor/Components/ESMaskCacheSpawnerComponent.cs
  Content.Shared/_ES/Masks/Traitor/ESSharedMaskCacheSystem.cs
  Resources/Locale/en-US/_ES/alerts/mask.ftl
  Resources/Locale/en-US/_ES/masks/masks.ftl
  Resources/Locale/en-US/_ES/masks/troupe/cache.ftl
  Resources/Prototypes/_ES/Alerts/mask.yml
  Resources/Prototypes/_ES/Entities/Markers/Spawners/traitor.yml
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/Ammunition/speedloaders.yml
  Resources/Prototypes/_ES/Fills/Crates/caches.yml
  Resources/Prototypes/_ES/Masks/masks.yml
  Resources/Textures/_ES/Interface/Alerts/cache.rsi/icon.png
  Resources/Textures/_ES/Interface/Alerts/cache.rsi/meta.json
  Resources/migration.yml
Labels: S: Untriaged, size/M, S: Needs Review

#186 Fix migrations being broken
  Content.Server/Maps/MapMigrationSystem.cs
Labels: S: Untriaged, S: Needs Review, size/XS

#188 Hydro stuff + robotics stuff + ore processor
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/_ES/Entities/Structures/Machines/vending.yml
  Resources/Textures/Structures/Machines/biofabricator.rsi/beaker.png
  Resources/Textures/Structures/Machines/biofabricator.rsi/building.png
  Resources/Textures/Structures/Machines/biofabricator.rsi/icon.png
  Resources/Textures/Structures/Machines/biofabricator.rsi/inserting.png
  Resources/Textures/Structures/Machines/biofabricator.rsi/meta.json
  Resources/Textures/Structures/Machines/biofabricator.rsi/panel.png
  Resources/Textures/Structures/Machines/biofabricator.rsi/unlit.png
  Resources/Textures/Structures/Machines/exosuit_fabricator.rsi/fab-active.png
  Resources/Textures/Structures/Machines/exosuit_fabricator.rsi/fab-idle.png
  Resources/Textures/Structures/Machines/exosuit_fabricator.rsi/fab-load.png
  Resources/Textures/Structures/Machines/exosuit_fabricator.rsi/fab-o.png
  Resources/Textures/Structures/Machines/exosuit_fabricator.rsi/meta.json
  Resources/Textures/Structures/Machines/mixer.rsi/mixer_broken.png
  Resources/Textures/Structures/Machines/mixer.rsi/mixer_empty.png
  Resources/Textures/Structures/Machines/ore_processor.rsi/building.png
  Resources/Textures/Structures/Machines/ore_processor.rsi/icon.png
  Resources/Textures/Structures/Machines/ore_processor.rsi/inserting.png
  Resources/Textures/Structures/Machines/ore_processor.rsi/meta.json
  Resources/Textures/Structures/Machines/ore_processor.rsi/panel.png
  Resources/Textures/Structures/Machines/ore_processor.rsi/unlit.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/meta.json
  Resources/Textures/Structures/Machines/seed_extractor.rsi/seedextractor-broken.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/seedextractor-off.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/seedextractor-screen-broken.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/seedextractor-unlit.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/seedextractor.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/spawner.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/traitcopier.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/traitgun.png
  Resources/Textures/Structures/Machines/seed_extractor.rsi/traitscanner.png
  Resources/Textures/_ES/Structures/Vendors/robotics.rsi/broken.png
  Resources/Textures/_ES/Structures/Vendors/robotics.rsi/deny-unshaded.png
  Resources/Textures/_ES/Structures/Vendors/robotics.rsi/meta.json
  Resources/Textures/_ES/Structures/Vendors/robotics.rsi/normal-unshaded.png
  Resources/Textures/_ES/Structures/Vendors/robotics.rsi/normal.png
  Resources/Textures/_ES/Structures/Vendors/robotics.rsi/off.png
  Resources/Textures/_ES/Structures/Vendors/robotics.rsi/panel.png
Labels: S: Untriaged, size/M, S: Needs Review

#191 ES spawner improvements
  Resources/Prototypes/Catalog/Fills/Lockers/wardrobe_colors.yml
  Resources/Prototypes/_ES/Catalog/Tables/back_items.yml
  Resources/Prototypes/_ES/Entities/Markers/Spawners/Random/maintenance.yml
  Resources/Textures/_ES/Markers/spawners.rsi/biohazard.png
  Resources/Textures/_ES/Markers/spawners.rsi/c10.png
  Resources/Textures/_ES/Markers/spawners.rsi/c20.png
  Resources/Textures/_ES/Markers/spawners.rsi/c25.png
  Resources/Textures/_ES/Markers/spawners.rsi/c30.png
  Resources/Textures/_ES/Markers/spawners.rsi/c40.png
  Resources/Textures/_ES/Markers/spawners.rsi/c50.png
  Resources/Textures/_ES/Markers/spawners.rsi/c60.png
  Resources/Textures/_ES/Markers/spawners.rsi/c70.png
  Resources/Textures/_ES/Markers/spawners.rsi/c75.png
  Resources/Textures/_ES/Markers/spawners.rsi/c80.png
  Resources/Textures/_ES/Markers/spawners.rsi/c90.png
  Resources/Textures/_ES/Markers/spawners.rsi/emergency-biohazard.png
  Resources/Textures/_ES/Markers/spawners.rsi/girder.png
  Resources/Textures/_ES/Markers/spawners.rsi/meta.json
Labels: S: Untriaged, size/M, S: Needs Review
