Repository EphemeralSpace/ephemeral-space, pull requests merged in 2025-08, with the labels that each got.

#57 Ushankas
  Resources/Prototypes/_ES/Entities/Clothing/Head/hats.yml
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka.rsi/equipped-HELMET.png
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka.rsi/meta.json
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka.rsi/up-equipped-HELMET.png
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka.rsi/ushanka.png
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka.rsi/ushankaup.png
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka_red.rsi/equipped-HELMET.png
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka_red.rsi/meta.json
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka_red.rsi/up-equipped-HELMET.png
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka_red.rsi/ushanka.png
  Resources/Textures/_ES/Clothing/Head/Hats/ushanka_red.rsi/ushankaup.png
Labels: S: Untriaged, size/S, S: Needs Review

#63 add a few russian jumpsuits
  Content.Server/Station/Systems/StationSpawningSystem.cs
  Resources/Prototypes/_ES/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/_ES/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/icon.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/inhand-left.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/inhand-right.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/meta.json
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/prisoner-equipped-INNERCLOTHING.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/prisoner-icon.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/prisoner-inhand-left.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/prisoner-inhand-right.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/trinkets-equipped-INNERCLOTHING.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/trinkets-icon.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/trinkets-inhand-left.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_color.rsi/trinkets-inhand-right.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_janitor.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_janitor.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_janitor.rsi/icon.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_janitor.rsi/inhand-left.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_janitor.rsi/inhand-right.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_janitor.rsi/meta.json
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_security.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_security.rsi/icon.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_security.rsi/inhand-left.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_security.rsi/inhand-right.png
  Resources/Textures/_ES/Clothing/Uniforms/Jumpsuit/ru_security.rsi/meta.json
Labels: S: Untriaged, size/M, S: Needs Review

#60 Add space pod prototypes
  Resources/Maps/_ES/Shuttles/space_pod.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/generators.yml
  Resources/Prototypes/_ES/Entities/Structures/Doors/airlocks.yml
  Resources/Prototypes/_ES/Entities/Structures/Shuttles/thrusters.yml
Labels: S: Untriaged, size/M, S: Needs Review

#64 gas thruster construction
  Resources/Locale/en-US/_ES/construction/graphs.ftl
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/_ES/Entities/Objects/Devices/engines.yml
  Resources/Prototypes/_ES/Entities/Objects/Devices/flatpack.yml
  Resources/Prototypes/_ES/Entities/Structures/Shuttles/thrusters.yml
  Resources/Prototypes/_ES/Lathe/devices.yml
  Resources/Prototypes/_ES/Lathe/packs.yml
  Resources/Prototypes/_ES/Recipes/Graphs/thruster.yml
  Resources/Prototypes/_ES/Recipes/thruster.yml
  Resources/Prototypes/_ES/tags.yml
  Resources/Textures/_ES/Objects/Devices/engine.rsi/icon-gas.png
  Resources/Textures/_ES/Objects/Devices/engine.rsi/icon-ion.png
  Resources/Textures/_ES/Objects/Devices/engine.rsi/inhand-left.png
  Resources/Textures/_ES/Objects/Devices/engine.rsi/inhand-right.png
  Resources/Textures/_ES/Objects/Devices/engine.rsi/meta.json
  Resources/Textures/_ES/Structures/Shuttles/thruster_frame.rsi/broken.png
  Resources/Textures/_ES/Structures/Shuttles/thruster_frame.rsi/frame.png
  Resources/Textures/_ES/Structures/Shuttles/thruster_frame.rsi/frame_filled.png
  Resources/Textures/_ES/Structures/Shuttles/thruster_frame.rsi/meta.json
  Resources/Textures/_ES/Structures/Shuttles/thruster_gas.rsi/base.png
  Resources/Textures/_ES/Structures/Shuttles/thruster_gas.rsi/meta.json
  Resources/Textures/_ES/Structures/Shuttles/thruster_gas.rsi/thrust.png
  Resources/Textures/_ES/Structures/Shuttles/thruster_gas.rsi/thrust_burn_unshaded.png
Labels: S: Untriaged, size/M, S: Needs Review

#66 Terminally Arrivals
  Content.Server/Shuttles/Systems/DockingSystem.Shuttle.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
  Content.Server/_ES/Arrivals/Components/ESArrivalsShuttleComponent.cs
  Content.Server/_ES/Arrivals/Components/ESStationArrivalsComponent.cs
  Content.Server/_ES/Arrivals/ESArrivalsSystem.cs
  Resources/Prototypes/_ES/Entities/Stations/base.yml
Labels: S: Untriaged, size/M, S: Needs Review

#68 Multistation Evacuation
  Content.Client/_ES/Evac/ESEvacSystem.cs
  Content.Client/_ES/Evac/Ui/ESEvacBeaconBui.cs
  Content.Client/_ES/Evac/Ui/ESEvacConsoleWindow.xaml
  Content.Client/_ES/Evac/Ui/ESEvacConsoleWindow.xaml.cs
  Content.Server/Station/Systems/StationSystem.cs
  Content.Server/_ES/Evac/ESEvacSystem.cs
  Content.Shared/Station/Components/StationMemberComponent.cs
  Content.Shared/_ES/Auditions/ESSharedAuditionsSystem.cs
  Content.Shared/_ES/CCVar/ESCVars.cs
  Content.Shared/_ES/Evac/Components/ESEvacConsoleComponent.cs
  Content.Shared/_ES/Evac/Components/ESEvacStationComponent.cs
  Content.Shared/_ES/Evac/ESSharedEvacSystem.cs
  Content.Shared/_ES/Spawning/ESSharedSpawningSystem.cs
  Resources/Locale/en-US/_ES/evac/evac.ftl
  Resources/Prototypes/_ES/Entities/Objects/Devices/circuits.yml
  Resources/Prototypes/_ES/Entities/Stations/base.yml
  Resources/Prototypes/_ES/Entities/Structures/Machines/computers.yml
Labels: S: Untriaged, size/M, S: Needs Review

#76 Add light in Space
  Content.Server/Shuttles/Systems/ShuttleSystem.cs
  Content.Server/_ES/Multistation/ESMultistationConfigPrototype.cs
  Content.Server/_ES/Multistation/ESMultistationSystem.cs
  Content.Shared/_ES/Light/Components/ESTileBasedRoofComponent.cs
  Content.Shared/_ES/Light/ESRoofSystem.cs
  Resources/Prototypes/_ES/Maps/multistation.yml
Labels: S: Untriaged, size/S, S: Needs Review

#75 Old SS13 style space parallax
  Content.Client/MainMenu/UI/MainMenuControl.xaml
  Resources/Prototypes/Parallaxes/default.yml
  Resources/Textures/_ES/Parallaxes/layer1.png
  Resources/Textures/_ES/Parallaxes/layer1.png.yml
  Resources/Textures/_ES/Parallaxes/layer2.png
  Resources/Textures/_ES/Parallaxes/layer2.png.yml
  Resources/Textures/_ES/Parallaxes/layer3.png
  Resources/Textures/_ES/Parallaxes/layer3.png.yml
  Resources/Textures/_ES/Parallaxes/layer4.png
  Resources/Textures/_ES/Parallaxes/layer4.png.yml
  Resources/Textures/_ES/Parallaxes/layer5.png
  Resources/Textures/_ES/Parallaxes/layer5.png.yml
  Resources/Textures/_ES/Parallaxes/layer6.png
  Resources/Textures/_ES/Parallaxes/layer6.png.yml
  Resources/Textures/_ES/Parallaxes/licences.txt
Labels: S: Untriaged, size/S, S: Needs Review

#78 Space bear sprite reverts
  Resources/Prototypes/Entities/Mobs/NPCs/space.yml
  Resources/Textures/Mobs/Animals/bear.rsi/bear.png
  Resources/Textures/Mobs/Animals/bear.rsi/bear_dead.png
  Resources/Textures/Mobs/Animals/bear.rsi/glow.png
  Resources/Textures/Mobs/Animals/bear.rsi/meta.json
Labels: S: Untriaged, size/S, S: Needs Review

#81 recolors red fancy table to match the carpet
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/full.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/meta.json
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_0.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_1.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_2.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_3.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_4.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_5.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_6.png
  Resources/Textures/Structures/Furniture/Tables/Fancy/red.rsi/state_7.png
Labels: S: Untriaged, S: Needs Review, size/XS

#83 Mild spawn menu tweaks
  Content.Client/_ES/Spawning/Ui/ESSpawningWindow.xaml.cs
  Content.Server/_ES/Spawning/ESSpawningSystem.cs
  Resources/Locale/en-US/_ES/spawning/spawn-menu.ftl
Labels: S: Untriaged, size/S, S: Needs Review

#93 Classic SS13 style labcoats
  Resources/Textures/Clothing/OuterClothing/Coats/labcoat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Coats/labcoat.rsi/icon-open.png
  Resources/Textures/Clothing/OuterClothing/Coats/labcoat.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Coats/labcoat.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Coats/labcoat.rsi/open-equipped-OUTERCLOTHING.png
Labels: S: Untriaged, S: Needs Review, size/XS

#100 Force separated game chat in all situations
  Content.Client/Gameplay/GameplayState.cs
Labels: S: Untriaged, S: Needs Review, size/XS

#108 Add easing to curtains
  Content.Client/_ES/Lobby/ESLobbyCurtainsUIController.cs
Labels: S: Untriaged, S: Needs Review, size/XS

#111 Cabinet Perspective Toolboxes (+ medkit changes)
  Resources/Prototypes/Entities/Objects/Tools/toolbox.yml
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/advkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/blackkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/brutekit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/burnkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/firstaid.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/meta.json
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/o2kit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/radkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/toxinkit.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_blue.rsi/icon-open.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_blue.rsi/icon.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_blue.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_blue.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_blue.rsi/meta.json
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_gold.rsi/icon-open.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_gold.rsi/icon.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_gold.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_gold.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_gold.rsi/meta.json
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_green.rsi/icon-open.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_green.rsi/icon.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_green.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_green.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_green.rsi/meta.json
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_red.rsi/icon-open.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_red.rsi/icon.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_red.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_red.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_red.rsi/meta.json
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_syn.rsi/icon-open.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_syn.rsi/icon.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_syn.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_syn.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_syn.rsi/meta.json
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_yellow.rsi/icon-open.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_yellow.rsi/icon.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_yellow.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_yellow.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Toolboxes/toolbox_yellow.rsi/meta.json
Labels: S: Untriaged, size/S, S: Needs Review

#112 Sound pass 1
  Resources/Audio/Effects/Footsteps/clownstep1.ogg
  Resources/Audio/Effects/Footsteps/clownstep2.ogg
  Resources/Audio/Effects/buckle.ogg
  Resources/Audio/Effects/unbuckle.ogg
  Resources/Audio/Items/bikehorn.ogg
  Resources/Audio/Machines/airlock_deny.ogg
  Resources/Audio/Machines/airlock_ext_close.ogg
  Resources/Audio/Machines/airlock_ext_open.ogg
  Resources/Audio/Machines/disposalflush.ogg
  Resources/Audio/_ES/Machines/airlock_close.ogg
  Resources/Audio/_ES/Machines/attributions.yml
  Resources/ConfigPresets/Build/development.toml
  Resources/ConfigPresets/_ES/ephemeralSpace.toml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/highsec.yml
  Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
  Resources/Prototypes/Entities/Structures/Lighting/base_lighting.yml
  Resources/Prototypes/Entities/Structures/Lighting/ground_lighting.yml
  Resources/Prototypes/Entities/Structures/Lighting/strobe_lighting.yml
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Entities/Structures/Power/cables.yml
  Resources/Prototypes/Entities/Structures/hydro_tray.yml
  Resources/Prototypes/Voice/speech_emote_sounds.yml
  Resources/Prototypes/_ES/Entities/Structures/Doors/indestructible.yml
Labels: S: Untriaged, size/M, S: Needs Review
