Repository EphemeralSpace/ephemeral-space, pull requests merged in 2025-09, with the labels that each got.

#116 Adjust throw spin behavior + more tile friction
  Content.Shared/Hands/Components/HandsComponent.cs
  Content.Shared/Maps/ContentTileDefinition.cs
  Content.Shared/Throwing/ThrowingSystem.cs
  Content.Shared/Throwing/ThrownItemSystem.cs
  Resources/Prototypes/Tiles/floors.yml
  Resources/Prototypes/Tiles/plating.yml
Labels: S: Untriaged, size/S, S: Needs Review

#117 Wallmount conditional visibility
  Content.Client/_ES/Wallmount/Components/ESWallMountTreeComponent.cs
  Content.Client/_ES/Wallmount/ESWallMountVisibilityOverlay.cs
  Content.Client/_ES/Wallmount/Systems/ESWallMountTreeSystem.cs
  Content.Client/_ES/Wallmount/Systems/ESWallMountVisibilitySystem.cs
  Content.Shared/Interaction/SharedInteractionSystem.cs
  Content.Shared/Wall/WallMountComponent.cs
  Content.Shared/_ES/Interaction/ESInteractionIgnoreAnchoredInTileComponent.cs
  Resources/Prototypes/Entities/Structures/Decoration/curtains.yml
  Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/bar_sign.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/WallmountMachines/screen.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/WallmountMachines/surveillance_camera.yml
  Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
  Resources/Prototypes/Entities/Structures/Windows/window.yml
  Resources/Prototypes/_ES/Entities/Structures/Windows/indestructible.yml
Labels: S: Untriaged, size/M, S: Needs Review

#141 Move old ghost light system to inherent lights + disable by default for ghosts
  Content.Client/Ghost/GhostSystem.cs
  Content.Client/_ES/Lighting/ESInherentLightComponent.cs
  Content.Client/_ES/Lighting/ESInherentLightSystem.cs
  Resources/Prototypes/Entities/Mobs/Player/observer.yml
  Resources/Prototypes/_ES/Entities/Mobs/moblights.yml
Labels: S: Untriaged, size/S, S: Needs Review

#144 Create troupe gamerules for handling mask assignment
  Content.Server/_ES/Masks/Components/ESTroupeRuleComponent.cs
  Content.Server/_ES/Masks/ESMaskSystem.cs
  Content.Shared/_ES/Auditions/ESSharedAuditionsSystem.cs
  Content.Shared/_ES/Masks/ESMaskPrototype.cs
  Content.Shared/_ES/Masks/ESTroupePrototype.cs
  Resources/Locale/en-US/_ES/gameticking/presets.ftl
  Resources/Locale/en-US/_ES/masks/troupes.ftl
  Resources/Prototypes/_ES/GameRules/presets.yml
  Resources/Prototypes/_ES/GameRules/troupes.yml
  Resources/Prototypes/_ES/Masks/masks.yml
  Resources/Prototypes/_ES/Masks/troupes.yml
Labels: S: Untriaged, size/M, S: Needs Review

#151 Fix computer rsi
  Resources/Textures/Structures/Machines/computers.rsi/meta.json
Labels: S: Untriaged, size/M, S: Needs Review

#145 Disposal unit resprite
  Resources/Prototypes/Entities/Structures/Piping/Disposal/units.yml
  Resources/Textures/Structures/Piping/disposal.rsi/condisposal.png
  Resources/Textures/Structures/Piping/disposal.rsi/conmailing.png
  Resources/Textures/Structures/Piping/disposal.rsi/disposal-charging.png
  Resources/Textures/Structures/Piping/disposal.rsi/disposal-flush.png
  Resources/Textures/Structures/Piping/disposal.rsi/disposal.png
  Resources/Textures/Structures/Piping/disposal.rsi/dispover-charge.png
  Resources/Textures/Structures/Piping/disposal.rsi/dispover-full.png
  Resources/Textures/Structures/Piping/disposal.rsi/dispover-handle.png
  Resources/Textures/Structures/Piping/disposal.rsi/dispover-ready.png
  Resources/Textures/Structures/Piping/disposal.rsi/mailing-charging.png
  Resources/Textures/Structures/Piping/disposal.rsi/mailing-flush.png
  Resources/Textures/Structures/Piping/disposal.rsi/mailing.png
  Resources/Textures/Structures/Piping/disposal.rsi/mailover-handle.png
  Resources/Textures/Structures/Piping/disposal.rsi/meta.json
Labels: S: Untriaged, S: Needs Review, size/XS

#150 Space heater resprite
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/portable.yml
  Resources/Textures/_ES/Structures/Piping/Atmospherics/Portable/portable_sheater.rsi/meta.json
  Resources/Textures/_ES/Structures/Piping/Atmospherics/Portable/portable_sheater.rsi/sheaterCool.png
  Resources/Textures/_ES/Structures/Piping/Atmospherics/Portable/portable_sheater.rsi/sheaterHeat.png
  Resources/Textures/_ES/Structures/Piping/Atmospherics/Portable/portable_sheater.rsi/sheaterOff.png
  Resources/Textures/_ES/Structures/Piping/Atmospherics/Portable/portable_sheater.rsi/sheaterPanelOpen.png
  Resources/Textures/_ES/Structures/Piping/Atmospherics/Portable/portable_sheater.rsi/sheaterStandby.png
Labels: S: Untriaged, size/S, S: Needs Review

#153 Fixes some incorrect meta.json stuff
  Resources/Textures/Structures/Machines/VendingMachines/tankdispenser.rsi/meta.json
  Resources/Textures/Structures/Machines/parts.rsi/meta.json
  Resources/Textures/Structures/Piping/disposal.rsi/meta.json
  Resources/Textures/Structures/Storage/tanks.rsi/meta.json
Labels: S: Untriaged, S: Needs Review, size/XS

#155 Autolathe, Protolathe, and Circuit Imprinter sprites
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Textures/Structures/Machines/autolathe.rsi/building.png
  Resources/Textures/Structures/Machines/autolathe.rsi/icon.png
  Resources/Textures/Structures/Machines/autolathe.rsi/inserting.png
  Resources/Textures/Structures/Machines/autolathe.rsi/meta.json
  Resources/Textures/Structures/Machines/autolathe.rsi/panel.png
  Resources/Textures/Structures/Machines/autolathe.rsi/unlit-building.png
  Resources/Textures/Structures/Machines/autolathe.rsi/unlit.png
  Resources/Textures/Structures/Machines/autolathe_hypercon.rsi/building.png
  Resources/Textures/Structures/Machines/autolathe_hypercon.rsi/icon.png
  Resources/Textures/Structures/Machines/autolathe_hypercon.rsi/inserting.png
  Resources/Textures/Structures/Machines/autolathe_hypercon.rsi/meta.json
  Resources/Textures/Structures/Machines/autolathe_hypercon.rsi/panel.png
  Resources/Textures/Structures/Machines/autolathe_hypercon.rsi/unlit-building.png
  Resources/Textures/Structures/Machines/autolathe_hypercon.rsi/unlit.png
  Resources/Textures/Structures/Machines/circuit_imprinter.rsi/building.png
  Resources/Textures/Structures/Machines/circuit_imprinter.rsi/icon.png
  Resources/Textures/Structures/Machines/circuit_imprinter.rsi/meta.json
  Resources/Textures/Structures/Machines/circuit_imprinter.rsi/panel.png
  Resources/Textures/Structures/Machines/circuit_imprinter.rsi/unlit.png
  Resources/Textures/Structures/Machines/circuit_imprinter_hypercon.rsi/building.png
  Resources/Textures/Structures/Machines/circuit_imprinter_hypercon.rsi/icon.png
  Resources/Textures/Structures/Machines/circuit_imprinter_hypercon.rsi/meta.json
  Resources/Textures/Structures/Machines/circuit_imprinter_hypercon.rsi/panel.png
  Resources/Textures/Structures/Machines/circuit_imprinter_hypercon.rsi/unlit.png
  Resources/Textures/Structures/Machines/protolathe.rsi/building.png
  Resources/Textures/Structures/Machines/protolathe.rsi/icon.png
  Resources/Textures/Structures/Machines/protolathe.rsi/inserting.png
  Resources/Textures/Structures/Machines/protolathe.rsi/meta.json
  Resources/Textures/Structures/Machines/protolathe.rsi/panel.png
  Resources/Textures/Structures/Machines/protolathe.rsi/unlit-building.png
  Resources/Textures/Structures/Machines/protolathe.rsi/unlit.png
  Resources/Textures/Structures/Machines/protolathe_hypercon.rsi/building.png
  Resources/Textures/Structures/Machines/protolathe_hypercon.rsi/icon.png
  Resources/Textures/Structures/Machines/protolathe_hypercon.rsi/inserting.png
  Resources/Textures/Structures/Machines/protolathe_hypercon.rsi/meta.json
  Resources/Textures/Structures/Machines/protolathe_hypercon.rsi/panel.png
  Resources/Textures/Structures/Machines/protolathe_hypercon.rsi/unlit-building.png
  Resources/Textures/Structures/Machines/protolathe_hypercon.rsi/unlit.png
Labels: S: Untriaged, size/M, S: Needs Review

#157 Tabletop computers
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/_ES/Entities/Structures/Machines/tabletop_computer.yml
  Resources/Textures/Structures/Machines/parts.rsi/meta.json
  Resources/Textures/Structures/Machines/parts.rsi/tabletop_0.png
  Resources/Textures/Structures/Machines/parts.rsi/tabletop_1.png
  Resources/Textures/Structures/Machines/parts.rsi/tabletop_2.png
  Resources/Textures/Structures/Machines/parts.rsi/tabletop_3.png
  Resources/Textures/Structures/Machines/parts.rsi/tabletop_4.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/broken.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/cameras.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/computer.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/crew.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/generic.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/generic_panel_open.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/id.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/medcomp.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/meta.json
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/request.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/security.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/supply.png
Labels: S: Untriaged, size/M, S: Needs Review

#156 Handguns (9mm, .357, silencer)
  Content.Shared/_ES/Weapons/Ranged/Attachments/Components/ESGunSoundAttachmentComponent.cs
  Content.Shared/_ES/Weapons/Ranged/Attachments/ESSharedGunAttachmentsSystem.cs
  Resources/Audio/_ES/Weapons/Guns/Gunshots/attributions.yml
  Resources/Audio/_ES/Weapons/Guns/Gunshots/pistol_shot_suppressed.ogg
  Resources/Locale/en-US/_ES/weapons/ranged/attachments.ftl
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/Ammunition/cartridge.yml
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/Ammunition/magazines.yml
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/Ammunition/speedloaders.yml
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/Attachments/silencer.yml
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/Projectiles/bullet.yml
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/pistol.yml
  Resources/Prototypes/_ES/Entities/Objects/Weapons/Guns/revolver.yml
  Resources/Prototypes/_ES/tags.yml
  Resources/Textures/_ES/Objects/Weapons/Guns/357.rsi/bolt-open.png
  Resources/Textures/_ES/Objects/Weapons/Guns/357.rsi/equipped-BELT.png
  Resources/Textures/_ES/Objects/Weapons/Guns/357.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_ES/Objects/Weapons/Guns/357.rsi/icon.png
  Resources/Textures/_ES/Objects/Weapons/Guns/357.rsi/inhand-left.png
  Resources/Textures/_ES/Objects/Weapons/Guns/357.rsi/inhand-right.png
  Resources/Textures/_ES/Objects/Weapons/Guns/357.rsi/meta.json
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/base.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/bolt-open.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/equipped-BELT.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/icon.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/inhand-left.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/inhand-right.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/mag-0.png
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/meta.json
  Resources/Textures/_ES/Objects/Weapons/Guns/9mm.rsi/silencer.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/base.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/inhand-left-mag.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/inhand-left-stripe.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/inhand-right-mag.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/inhand-right-stripe.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/mag-1.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/mag-2.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/mag-3.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/mag-4.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/mag-5.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/meta.json
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/red-icon.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Ammunition/9mm_mag.rsi/stripe.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Attachments/silencer.rsi/icon.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Attachments/silencer.rsi/inhand-left.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Attachments/silencer.rsi/inhand-right.png
  Resources/Textures/_ES/Objects/Weapons/Guns/Attachments/silencer.rsi/meta.json
Labels: S: Untriaged, size/M, S: Needs Review

#159 Baystation reinforced floor sprites ( +kills multitool unshaded layer)
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/Tiles/floors.yml
  Resources/Textures/Structures/Machines/circuit_imprinter.rsi/meta.json
  Resources/Textures/_ES/Tiles/attributions.yml
  Resources/Textures/_ES/Tiles/reinforced.png
Labels: S: Untriaged, size/S, S: Needs Review

#161 Adds missing wardrobes and fills
  Resources/Prototypes/_ES/Entities/Structures/Storage/wardrobe.yml
  Resources/Prototypes/_ES/Fills/Lockers/wardrobe_job.yml
Labels: S: Untriaged, size/M, S: Needs Review

#163 Cargo Request System
  Content.Client/_ES/Cargo/Requests/ESCargoRequestSystem.cs
  Content.Client/_ES/Cargo/Requests/Ui/ESCargoRequestConsoleBui.cs
  Content.Client/_ES/Cargo/Requests/Ui/ESCargoRequestConsoleWindow.xaml
  Content.Client/_ES/Cargo/Requests/Ui/ESCargoRequestConsoleWindow.xaml.cs
  Content.Client/_ES/Cargo/Requests/Ui/ESRequestCreationWindow.xaml
  Content.Client/_ES/Cargo/Requests/Ui/ESRequestCreationWindow.xaml.cs
  Content.Client/_ES/Cargo/Requests/Ui/ESRequestEntry.xaml
  Content.Client/_ES/Cargo/Requests/Ui/ESRequestEntry.xaml.cs
  Content.Server/_ES/Cargo/Requests/ESCargoRequestsSystem.cs
  Content.Shared/_ES/Cargo/Requests/Components/ESCargoRequestConsoleComponent.cs
  Content.Shared/_ES/Cargo/Requests/Components/ESCargoRequestStationComponent.cs
  Content.Shared/_ES/Cargo/Requests/ESSharedCargoRequestSystem.cs
  Resources/Locale/en-US/_ES/cargo/requests.ftl
  Resources/Prototypes/_ES/Entities/Objects/Devices/circuits.yml
  Resources/Prototypes/_ES/Entities/Stations/base.yml
  Resources/Prototypes/_ES/Entities/Structures/Machines/computers.yml
  Resources/Prototypes/_ES/Entities/Structures/Machines/tabletop_computer.yml
  Resources/Textures/_ES/Structures/Machines/computer.rsi/meta.json
  Resources/Textures/_ES/Structures/Machines/computer.rsi/request-0.png
  Resources/Textures/_ES/Structures/Machines/computer.rsi/request-1.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/meta.json
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/request-0.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/request-1.png
  Resources/Textures/_ES/Structures/Machines/tabletop_computer.rsi/request.png
Labels: S: Untriaged, size/M, S: Needs Review

#167 Remove sprite offset from potted plants
  Resources/Prototypes/Entities/Structures/Furniture/potted_plants.yml
Labels: S: Untriaged, S: Needs Review, size/XS

#170 Add more customization options to fire modes
  Content.Shared/Weapons/Ranged/Components/BatteryWeaponFireModesComponent.cs
  Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
Labels: S: Untriaged, size/S, S: Needs Review
